#!/usr/bin/env ruby
# Modified by me from Tammer Saleh: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [
  "git://github.com/altercation/vim-colors-solarized.git",
  "git://github.com/kana/vim-textobj-user.git",
  "git://github.com/kien/ctrlp.vim.git",
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/nelstrom/vim-textobj-rubyblock.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/slack/vim-align.git",
  "git://github.com/slack/vim-bufexplorer.git",
  "git://github.com/tpope/vim-bundler.git",
  "git://github.com/tpope/vim-commentary.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/vim-ruby/vim-ruby.git"
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  if Dir.exists?(dir)
    puts "Updating #{url} in #{dir}"
    %x{ set -x; pushd #{dir}; git fetch && git pull --rebase origin master; popd }
  else
    puts "  Unpacking #{url} into #{dir}"
    `git clone #{url} #{dir}`
  end
end
