## run for login shells

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# default ruby plz
chruby ruby-2.3

source "${HOME}/google/google-cloud-sdk/path.bash.inc"
source "${HOME}/google/google-cloud-sdk/completion.bash.inc"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

if [[ -d "$HOME/Developer" ]] ; then
    PATH="$HOME/Developer/sbin:$HOME/Developer/bin:$PATH"
fi

if [[ -d "$HOME/Developer/lib/node_modules" ]] ; then
  NODE_PATH="$HOME/Developer/lib/node_modules"
fi

## PATH
PATH=/usr/local/bin:$PATH

if [[ -d "$HOME/.files/bin" ]] ; then
    PATH="$HOME/.files/bin:$PATH"
fi

## set PATH so it includes user's private bin if it exists
if [[ -d "$HOME/bin" ]] ; then
    PATH="$HOME/bin:$PATH"
fi

if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
    source ~/.gnupg/.gpg-agent-info
    export GPG_AGENT_INFO
else
    eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
fi
