## run for login shells

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# default ruby plz
chruby ruby-2.2

# The next line updates PATH for the Google Cloud SDK.
if [[ -e "$HOME/google/google-cloudsdk" ]]; then
    source "${HOME}/google/google-cloud-sdk/path.bash.inc"
    source "${HOME}/google/google-cloud-sdk/completion.bash.inc"
fi
